// sample vocabulary data
export const vocabulary = [
  {
    word: "mangan",
    translation: "makan",
    level: "ngoko",
    example: "Aku arep mangan saiki.",
    exampleTranslation: "Aku mau makan sekarang.",
    verified: true,
    id: 'rec_001',
    user_id: 'user_001',
    user_name: 'Siti Nurhaliza',
    mission_id: 'mission_001',
    audio_url: '/audio/sample1.mp3',
    transcript_ai: 'Gak ana uwong sing bisa nglirwakake kabeh',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-15T10:30:00Z',
    contribution_type: 'voice',
    languageName: 'Jawa',
    dialect: 'Jawa Ngoko',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: '',
    created_by: 'contributor@gmail.com',
  },
  {
    word: "nedha",
    translation: "makan",
    level: "krama",
    example: "Kula badhe nedha rumiyin.",
    exampleTranslation: "Saya akan makan terlebih dahulu.",
    verified: false,
  },
  {
    word: "turu",
    translation: "tidur",
    level: "ngoko",
    example: "Dheweke lagi turu ing kamare.",
    exampleTranslation: "Dia sedang tidur di kamarnya.",
    verified: true,
  },
  {
    word: "tilem",
    translation: "tidur",
    level: "krama",
    example: "Bapak sampun tilem wiwit mau.",
    exampleTranslation: "Ayah sudah tidur sejak tadi.",
    verified: true,
  },
  {
    word: "omah",
    translation: "rumah",
    level: "ngoko",
    example: "Iki omahku.",
    exampleTranslation: "Ini rumahku.",
    verified: true,
  },
  {
    word: "gria",
    translation: "rumah",
    level: "krama",
    example: "Kula sowan ing gria panjenengan.",
    exampleTranslation: "Saya berkunjung ke rumah Anda.",
    verified: false,
  },
  {
    word: "mlaku",
    translation: "berjalan",
    level: "ngoko",
    example: "Ayo mlaku menyang pasar.",
    exampleTranslation: "Ayo berjalan ke pasar.",
    verified: false,
  },
  {
    word: "mlampah",
    translation: "berjalan",
    level: "krama",
    example: "Mboten kenging mlampah kesusu.",
    exampleTranslation: "Tidak boleh berjalan terburu-buru.",
    verified: false,
  },
  {
    word: "kowe",
    translation: "kamu",
    level: "ngoko",
    example: "Kowe wis mangan durung?",
    exampleTranslation: "Kamu sudah makan belum?",
    verified: true,
  },
  {
    word: "sampean",
    translation: "Anda",
    level: "madya",
    example: "Sampean arep lunga endi?",
    exampleTranslation: "Anda mau pergi ke mana?",
    verified: false,
  },
  {
    word: "panjenengan",
    translation: "Anda",
    level: "krama",
    example: "Panjenengan badhe tindak pundi?",
    exampleTranslation: "Anda hendak pergi ke mana?",
    verified: true,
  },
  {
    word: "adus",
    translation: "mandi",
    level: "ngoko",
    example: "Aku arep adus dhisik.",
    exampleTranslation: "Aku mau mandi dulu.",
    verified: true,
  },
  {
    word: "siram",
    translation: "mandi",
    level: "krama",
    example: "Nenek nembe siram.",
    exampleTranslation: "Nenek baru saja mandi.",
    verified: false,
  },
  {
    word: "lungguh",
    translation: "duduk",
    level: "krama",
    example: "Mangga lungguh rumiyin.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
  },
  {
    word: "lunggak-lungguh",
    translation: "duduk (ngoko halus)",
    level: "madya",
    example: "Monggo lunggak-lungguh sek.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
  }
];

// sample language archive detail
export const languageArchive = [
  {
    id: "1",
    name: "Bahasa Jawa",
    region: "Jawa Tengah, Jawa Timur",
    regionId: ["33", "35"],
    ethnic: "Jawa",
    speakers: "84,3 juta",
    status: "recorded",
    vocabularyCount: 2500,
    audioCount: 1200,
    contributorCount: 300,
  },
  {
    id: "2",
    name: "Bahasa Sunda",
    region: "Jawa Barat",
    regionId: ["32"],
    ethnic: "Sunda",
    speakers: "42 juta",
    status: "recorded",
    vocabularyCount: 1800,
    audioCount: 950,
    contributorCount: 200,
  },
  {
    id: "3",
    name: "Bahasa Batak Toba",
    region: "Sumatera Utara",
    regionId: ["12"],
    ethnic: "Batak",
    speakers: "2 juta",
    status: "not_recorded",
    vocabularyCount: 1200,
    audioCount: 600,
    contributorCount: 140,
  },
  {
    id: "4",
    name: "Bahasa Bali",
    region: "Bali",
    regionId: ["51"],
    ethnic: "Bali",
    speakers: "3,3 juta",
    status: "recorded",
    vocabularyCount: 1500,
    audioCount: 750,
    contributorCount: 150,
  },
  {
    id: "5",
    name: "Bahasa Minangkabau",
    region: "Sumatera Barat",
    regionId: ["13"],
    ethnic: "Minangkabau",
    speakers: "5,5 juta",
    status: "recorded",
    vocabularyCount: 1600,
    audioCount: 800,
    contributorCount: 200,
  },
  {
    id: "6",
    name: "Bahasa Bugis",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Bugis",
    speakers: "5 juta",
    status: "not_recorded",
    vocabularyCount: 1100,
    audioCount: 550,
    contributorCount: 100,
  },
  {
    id: "7",
    name: "Bahasa Sasak",
    region: "Nusa Tenggara Barat",
    regionId: ["52"],
    ethnic: "Sasak",
    speakers: "2,7 juta",
    status: "recorded",
    vocabularyCount: 900,
    audioCount: 450,
    contributorCount: 120,
  },
  {
    id: "8",
    name: "Bahasa Dayak Ngaju",
    region: "Kalimantan Tengah",
    regionId: ["62"],
    ethnic: "Dayak",
    speakers: "900 ribu",
    status: "not_recorded",
    vocabularyCount: 750,
    audioCount: 380,
    contributorCount: 50,
  },
  {
    id: "9",
    name: "Bahasa Toraja",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Toraja",
    speakers: "1,2 juta",
    status: "not_recorded",
    vocabularyCount: 850,
    audioCount: 420,
    contributorCount: 55,
  },
];

// sample leaderboard data
export const leaderboard = [
  { rank: 1, name: "Ibu Siti Nurhaliza", region: "Jawa Tengah", contributions: 342, xp: 3420 },
  { rank: 2, name: "Bapak Ahmad Dahlan", region: "Sumatera Barat", contributions: 298, xp: 2980 },
  { rank: 3, name: "Ni Luh Ketut Ayu", region: "Bali", contributions: 276, xp: 2760 },
  { rank: 4, name: "Raden Mas Wijaya", region: "Jawa Barat", contributions: 254, xp: 2540 },
  { rank: 5, name: "Andi Mappasessu", region: "Sulawesi Selatan", contributions: 231, xp: 2310 },
];

// sample missions data
export const mockMissions = [
  {
    id: '1',
    title: '5 Kata Dasar Daerahmu',
    description: 'Kontributor diminta menambahkan 5 kosakata dasar dari bahasa daerahnya, lengkap dengan arti dan contoh kalimat.',
    reward_xp: 25,
    type: 'contributor',
    difficulty: 'easy',
    done: true,
  },
  {
    id: '2',
    title: 'Rekam 3 Kalimat dengan Dialek Aslimu',
    description: 'Pengguna merekam 3 kalimat natural menggunakan logat/dialek daerah tertentu.',
    reward_xp: 30,
    type: 'contributor',
    difficulty: 'easy',
    done: true,
  },
  {
    id: '3',
    title: '2 Bahasa Daerah Berbeda Provinsi',
    description: 'Buat kosakata bahasa daerah di 2 bahasa daerah yang berbeda provinsi.',
    reward_xp: 50,
    type: 'contributor',
    difficulty: 'medium',
    done: false,
  },
  {
    id: '4',
    title: '3 Kosakata Terverifikasi',
    description: 'Buat 3 kosakata baru dan tunggu hingga terverifikasi oleh validator.',
    reward_xp: 100,
    type: 'contributor',
    difficulty: 'hard',
    done: false,
  },
  {
    id: '5',
    title: '3 Bahasa Daerah Berbeda',
    description: 'Buat kosakata di 3 bahasa daerah yang berbeda.',
    reward_xp: 75,
    type: 'contributor',
    difficulty: 'medium',
    done: false,
  }
];

// sample recordings data
export const mockRecordings = [
  {
    id: 'rec_001',
    user_id: 'user_001',
    user_name: 'Siti Nurhaliza',
    mission_id: 'mission_001',
    audio_url: '/audio/sample1.mp3',
    transcript_ai: 'Gak ana uwong sing bisa nglirwakake kabeh',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-15T10:30:00Z',
    contribution_type: 'voice',
    languageName: 'Jawa',
    dialect: 'Jawa Ngoko',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: '',
  },
  {
    id: 'rec_002',
    user_id: 'user_002',
    user_name: 'Ahmad Dahlan',
    mission_id: 'mission_002',
    audio_url: '/audio/sample2.mp3',
    transcript_ai: 'Rang mudo kudu tau tatakramo',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-16T14:20:00Z',
    contribution_type: 'voice',
    languageName: 'Sunda',
    dialect: 'Sunda Priangan',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_003',
    user_id: 'user_003',
    user_name: 'Luh Ketut Ayu',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-17T09:15:00Z',
    contribution_type: 'vocabulary',
    languageName: 'Bali',
    dialect: 'Bali Alus',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_004',
    user_id: 'user_004',
    user_name: 'Raden Wijaya',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'approved',
    validated_at: '2024-01-18T11:00:00Z',
    created_at: '2024-01-17T16:45:00Z',
    contribution_type: 'folktale',
    languageName: 'Jawa',
    dialect: 'Jawa Krama',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_005',
    user_id: 'user_005',
    user_name: 'Andi Mappasessu',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'approved',
    validated_at: '2024-01-19T14:30:00Z',
    created_at: '2024-01-18T08:20:00Z',
    contribution_type: 'vocabulary',
    languageName: 'Bugis',
    dialect: 'Bugis Bone',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'bugis',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_006',
    user_id: 'user_006',
    user_name: 'Putu Gede Agung',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-19T16:00:00Z',
    contribution_type: 'translation',
    languageName: 'Bali',
    dialect: 'Bali Lumrah',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    sentenceAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  }
];

// sample province data
export const provinceList = [
  { value: 1, label: "Aceh" },
  { value: 2, label: "Sumatera Barat" },
  { value: 3, label: "Jawa Tengah" },
  { value: 4, label: "Jawa Timur" },
  { value: 5, label: "Bali" },
  { value: 6, label: "Daerah Istimewa Yogyakarta"}
];

// sample region data
export const regionList = [
  { value: 1, label: "Purbalingga" },
  { value: 2, label: "Batam" },
  { value: 3, label: "Sleman" },
  { value: 4, label: "Bantul" },
  { value: 5, label: "Pekanbaru" },
  { value: 6, label: "Yogyakarta" },
];