// sample vocabulary data
export const vocabulary = [
  {
    word: "mangan",
    translation: "makan",
    level: "ngoko",
    example: "Aku arep mangan saiki.",
    exampleTranslation: "Aku mau makan sekarang.",
    verified: true,
  },
  {
    word: "nedha",
    translation: "makan",
    level: "krama",
    example: "Kula badhe nedha rumiyin.",
    exampleTranslation: "Saya akan makan terlebih dahulu.",
    verified: false,
  },
  {
    word: "turu",
    translation: "tidur",
    level: "ngoko",
    example: "Dheweke lagi turu ing kamare.",
    exampleTranslation: "Dia sedang tidur di kamarnya.",
    verified: true,
  },
  {
    word: "tilem",
    translation: "tidur",
    level: "krama",
    example: "Bapak sampun tilem wiwit mau.",
    exampleTranslation: "Ayah sudah tidur sejak tadi.",
    verified: true,
  },
  {
    word: "omah",
    translation: "rumah",
    level: "ngoko",
    example: "Iki omahku.",
    exampleTranslation: "Ini rumahku.",
    verified: true,
  },
  {
    word: "gria",
    translation: "rumah",
    level: "krama",
    example: "Kula sowan ing gria panjenengan.",
    exampleTranslation: "Saya berkunjung ke rumah Anda.",
    verified: false,
  },
  {
    word: "mlaku",
    translation: "berjalan",
    level: "ngoko",
    example: "Ayo mlaku menyang pasar.",
    exampleTranslation: "Ayo berjalan ke pasar.",
    verified: false,
  },
  {
    word: "mlampah",
    translation: "berjalan",
    level: "krama",
    example: "Mboten kenging mlampah kesusu.",
    exampleTranslation: "Tidak boleh berjalan terburu-buru.",
    verified: false,
  },
  {
    word: "kowe",
    translation: "kamu",
    level: "ngoko",
    example: "Kowe wis mangan durung?",
    exampleTranslation: "Kamu sudah makan belum?",
    verified: true,
  },
  {
    word: "sampean",
    translation: "Anda",
    level: "madya",
    example: "Sampean arep lunga endi?",
    exampleTranslation: "Anda mau pergi ke mana?",
    verified: false,
  },
  {
    word: "panjenengan",
    translation: "Anda",
    level: "krama",
    example: "Panjenengan badhe tindak pundi?",
    exampleTranslation: "Anda hendak pergi ke mana?",
    verified: true,
  },
  {
    word: "adus",
    translation: "mandi",
    level: "ngoko",
    example: "Aku arep adus dhisik.",
    exampleTranslation: "Aku mau mandi dulu.",
    verified: true,
  },
  {
    word: "siram",
    translation: "mandi",
    level: "krama",
    example: "Nenek nembe siram.",
    exampleTranslation: "Nenek baru saja mandi.",
    verified: false,
  },
  {
    word: "lungguh",
    translation: "duduk",
    level: "krama",
    example: "Mangga lungguh rumiyin.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
  },
  {
    word: "lunggak-lungguh",
    translation: "duduk (ngoko halus)",
    level: "madya",
    example: "Monggo lunggak-lungguh sek.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
  }
];

// sample language archive detail
export const languageArchive = [
  {
    id: 1,
    name: "Bahasa Jawa",
    region: "Jawa Tengah, Jawa Timur",
    regionId: ["33", "35"],
    ethnic: "Jawa",
    speakers: "84,3 juta",
    status: "recorded",
    vocabularyCount: 2500,
    audioCount: 1200,
    contributorCount: 300,
  },
  {
    id: 2,
    name: "Bahasa Sunda",
    region: "Jawa Barat",
    regionId: ["32"],
    ethnic: "Sunda",
    speakers: "42 juta",
    status: "recorded",
    vocabularyCount: 1800,
    audioCount: 950,
    contributorCount: 200,
  },
  {
    id: 3,
    name: "Bahasa Batak Toba",
    region: "Sumatera Utara",
    regionId: ["12"],
    ethnic: "Batak",
    speakers: "2 juta",
    status: "not_recorded",
    vocabularyCount: 1200,
    audioCount: 600,
    contributorCount: 140,
  },
  {
    id: 4,
    name: "Bahasa Bali",
    region: "Bali",
    regionId: ["51"],
    ethnic: "Bali",
    speakers: "3,3 juta",
    status: "recorded",
    vocabularyCount: 1500,
    audioCount: 750,
    contributorCount: 150,
  },
  {
    id: 5,
    name: "Bahasa Minangkabau",
    region: "Sumatera Barat",
    regionId: ["13"],
    ethnic: "Minangkabau",
    speakers: "5,5 juta",
    status: "recorded",
    vocabularyCount: 1600,
    audioCount: 800,
    contributorCount: 200,
  },
  {
    id: 6,
    name: "Bahasa Bugis",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Bugis",
    speakers: "5 juta",
    status: "not_recorded",
    vocabularyCount: 1100,
    audioCount: 550,
    contributorCount: 100,
  },
  {
    id: 7,
    name: "Bahasa Sasak",
    region: "Nusa Tenggara Barat",
    regionId: ["52"],
    ethnic: "Sasak",
    speakers: "2,7 juta",
    status: "recorded",
    vocabularyCount: 900,
    audioCount: 450,
    contributorCount: 120,
  },
  {
    id: 8,
    name: "Bahasa Dayak Ngaju",
    region: "Kalimantan Tengah",
    regionId: ["62"],
    ethnic: "Dayak",
    speakers: "900 ribu",
    status: "not_recorded",
    vocabularyCount: 750,
    audioCount: 380,
    contributorCount: 50,
  },
  {
    id: 9,
    name: "Bahasa Toraja",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Toraja",
    speakers: "1,2 juta",
    status: "not_recorded",
    vocabularyCount: 850,
    audioCount: 420,
    contributorCount: 55,
  },
];

// sample leaderboard data
export const leaderboard = [
  { rank: 1, name: "Ibu Siti Nurhaliza", region: "Jawa Tengah", contributions: 342 },
  { rank: 2, name: "Bapak Ahmad Dahlan", region: "Sumatera Barat", contributions: 298 },
  { rank: 3, name: "Ni Luh Ketut Ayu", region: "Bali", contributions: 276 },
  { rank: 4, name: "Raden Mas Wijaya", region: "Jawa Barat", contributions: 254 },
  { rank: 5, name: "Andi Mappasessu", region: "Sulawesi Selatan", contributions: 231 },
];