// sample vocabulary data
export const vocabulary: any = [
  {
    id: 1,
    word: "mangan",
    translation: "makan",
    level: "ngoko",
    example: "Aku arep mangan saiki.",
    exampleTranslation: "Aku mau makan sekarang.",
    verified: true,
    user_id: 'user_001',
    user_name: 'Siti Nurhaliza',
    mission_id: 'mission_001',
    audio_url: '/audio/sample1.mp3',
    transcript_ai: 'Gak ana uwong sing bisa nglirwakake kabeh',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-15T10:30:00Z',
    contribution_type: 'voice',
    languageName: 'Jawa',
    dialect: 'Jawa Ngoko',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
    created_by: 'contributor@gmail.com',
    like: 123,
    comment: 1,
  },
  {
    id: 2,
    word: "nedha",
    translation: "makan",
    level: "krama",
    example: "Kula badhe nedha rumiyin.",
    exampleTranslation: "Saya akan makan terlebih dahulu.",
    verified: false,
    like: 12,
    comment: 12,
  },
  {
    id: 3,
    word: "turu",
    translation: "tidur",
    level: "ngoko",
    example: "Dheweke lagi turu ing kamare.",
    exampleTranslation: "Dia sedang tidur di kamarnya.",
    verified: true,
    like: 33,
    comment: 4,
  },
  {
    id: 4,
    word: "tilem",
    translation: "tidur",
    level: "krama",
    example: "Bapak sampun tilem wiwit mau.",
    exampleTranslation: "Ayah sudah tidur sejak tadi.",
    verified: true,
    like: 133,
    comment: 0,
  },
  {
    id: 5,
    word: "omah",
    translation: "rumah",
    level: "ngoko",
    example: "Iki omahku.",
    exampleTranslation: "Ini rumahku.",
    verified: true,
    like: 1,
    comment: 2,
  },
  {
    id: 6,
    word: "gria",
    translation: "rumah",
    level: "krama",
    example: "Kula sowan ing gria panjenengan.",
    exampleTranslation: "Saya berkunjung ke rumah Anda.",
    verified: false,
    comment: 0,
  },
  {
    id: 7,
    word: "mlaku",
    translation: "berjalan",
    level: "ngoko",
    example: "Ayo mlaku menyang pasar.",
    exampleTranslation: "Ayo berjalan ke pasar.",
    verified: false,
    like: 10,
    comment: 0,
  },
  {
    id: 8,
    word: "mlampah",
    translation: "berjalan",
    level: "krama",
    example: "Mboten kenging mlampah kesusu.",
    exampleTranslation: "Tidak boleh berjalan terburu-buru.",
    verified: false,
    like: 1,
    comment: 22,
  },
  {
    id: 9,
    word: "kowe",
    translation: "kamu",
    level: "ngoko",
    example: "Kowe wis mangan durung?",
    exampleTranslation: "Kamu sudah makan belum?",
    verified: true,
    like: 90,
    comment: 1,
  },
  {
    id: 10,
    word: "sampean",
    translation: "Anda",
    level: "madya",
    example: "Sampean arep lunga endi?",
    exampleTranslation: "Anda mau pergi ke mana?",
    verified: false,
    like: 0,
    comment: 1,
  },
  {
    id: 11,
    word: "panjenengan",
    translation: "Anda",
    level: "krama",
    example: "Panjenengan badhe tindak pundi?",
    exampleTranslation: "Anda hendak pergi ke mana?",
    verified: true,
    like: 1,
    comment: 2,
  },
  {
    id: 12,
    word: "adus",
    translation: "mandi",
    level: "ngoko",
    example: "Aku arep adus dhisik.",
    exampleTranslation: "Aku mau mandi dulu.",
    verified: true,
    like: 1,
    comment: 2,
  },
  {
    id: 13,
    word: "siram",
    translation: "mandi",
    level: "krama",
    example: "Nenek nembe siram.",
    exampleTranslation: "Nenek baru saja mandi.",
    verified: false,
    like: 11,
    comment: 21,
  },
  {
    id: 14,
    word: "lungguh",
    translation: "duduk",
    level: "krama",
    example: "Mangga lungguh rumiyin.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
    like: 250,
    comment: 2,
  },
  {
    id: 15,
    word: "lunggak-lungguh",
    translation: "duduk (ngoko halus)",
    level: "madya",
    example: "Monggo lunggak-lungguh sek.",
    exampleTranslation: "Silakan duduk dulu.",
    verified: false,
    like: 0,
    comment: 0,
  }
];

// sample language archive detail
export const languageArchive = [
  {
    id: "1",
    name: "Bahasa Jawa",
    region: "Jawa Tengah, Jawa Timur",
    regionId: ["33", "35"],
    ethnic: "Jawa",
    speakers: "84,3 juta",
    status: "recorded",
    vocabularyCount: 2500,
    audioCount: 1200,
    contributorCount: 300,
  },
  {
    id: "10",
    name: "Bahasa Jawa Banyumasan",
    region: "Jawa Tengah",
    regionId: ["33"],
    ethnic: "Jawa",
    speakers: "12 juta",
    status: "recorded",
    vocabularyCount: 500,
    audioCount: 200,
    contributorCount: 50,
  },
  {
    id: "2",
    name: "Bahasa Sunda",
    region: "Jawa Barat",
    regionId: ["32"],
    ethnic: "Sunda",
    speakers: "42 juta",
    status: "not_recorded",
    vocabularyCount: 1800,
    audioCount: 950,
    contributorCount: 200,
  },
  {
    id: "3",
    name: "Bahasa Batak Toba",
    region: "Sumatera Utara",
    regionId: ["12"],
    ethnic: "Batak",
    speakers: "2 juta",
    status: "not_recorded",
    vocabularyCount: 1200,
    audioCount: 600,
    contributorCount: 140,
  },
  {
    id: "4",
    name: "Bahasa Bali",
    region: "Bali",
    regionId: ["51"],
    ethnic: "Bali",
    speakers: "3,3 juta",
    status: "not_recorded",
    vocabularyCount: 1500,
    audioCount: 750,
    contributorCount: 150,
  },
  {
    id: "5",
    name: "Bahasa Minangkabau",
    region: "Sumatera Barat",
    regionId: ["13"],
    ethnic: "Minangkabau",
    speakers: "5,5 juta",
    status: "not_recorded",
    vocabularyCount: 1600,
    audioCount: 800,
    contributorCount: 200,
  },
  {
    id: "6",
    name: "Bahasa Bugis",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Bugis",
    speakers: "5 juta",
    status: "not_recorded",
    vocabularyCount: 1100,
    audioCount: 550,
    contributorCount: 100,
  },
  {
    id: "7",
    name: "Bahasa Sasak",
    region: "Nusa Tenggara Barat",
    regionId: ["52"],
    ethnic: "Sasak",
    speakers: "2,7 juta",
    status: "not_recorded",
    vocabularyCount: 900,
    audioCount: 450,
    contributorCount: 120,
  },
  {
    id: "8",
    name: "Bahasa Dayak Ngaju",
    region: "Kalimantan Tengah",
    regionId: ["62"],
    ethnic: "Dayak",
    speakers: "900 ribu",
    status: "not_recorded",
    vocabularyCount: 750,
    audioCount: 380,
    contributorCount: 50,
  },
  {
    id: "9",
    name: "Bahasa Toraja",
    region: "Sulawesi Selatan",
    regionId: ["73"],
    ethnic: "Toraja",
    speakers: "1,2 juta",
    status: "not_recorded",
    vocabularyCount: 850,
    audioCount: 420,
    contributorCount: 55,
  },
];

// sample leaderboard data
export const leaderboard = [
  { rank: 1, name: "Ibu Siti Nurhaliza", region: "Jawa Tengah", contributions: 342, points: 3420 },
  { rank: 2, name: "Bapak Ahmad Dahlan", region: "Sumatera Barat", contributions: 298, points: 2980 },
  { rank: 3, name: "Ni Luh Ketut Ayu", region: "Bali", contributions: 276, points: 2760 },
  { rank: 4, name: "Raden Mas Wijaya", region: "Jawa Barat", contributions: 254, points: 2540 },
  { rank: 5, name: "Andi Mappasessu", region: "Sulawesi Selatan", contributions: 231, points: 2310 },
];

// sample missions data
export const mockMissions = [
  {
    id: '1',
    title: '5 Kata Dasar Daerahmu',
    description: 'Kontributor diminta menambahkan 5 kosakata dasar dari bahasa daerahnya, lengkap dengan arti dan contoh kalimat.',
    reward_points: 25,
    reward_coins: 500,
    type: 'contributor',
    difficulty: 'easy',
    done: true,
  },
  {
    id: '2',
    title: 'Rekam 3 Kalimat dengan Dialek Aslimu',
    description: 'Pengguna merekam 3 kalimat natural menggunakan logat/dialek daerah tertentu.',
    reward_points: 30,
    reward_coins: 600,
    type: 'contributor',
    difficulty: 'easy',
    done: true,
  },
  {
    id: '3',
    title: '2 Bahasa Daerah Berbeda Provinsi',
    description: 'Buat kosakata bahasa daerah di 2 bahasa daerah yang berbeda provinsi.',
    reward_points: 50,
    reward_coins: 1000,
    type: 'contributor',
    difficulty: 'medium',
    done: false,
  },
  {
    id: '4',
    title: '3 Kosakata Terverifikasi',
    description: 'Buat 3 kosakata baru dan tunggu hingga terverifikasi oleh validator.',
    reward_points: 100,
    reward_coins: 2000,
    type: 'contributor',
    difficulty: 'hard',
    done: false,
  },
  {
    id: '5',
    title: '3 Bahasa Daerah Berbeda',
    description: 'Buat kosakata di 3 bahasa daerah yang berbeda.',
    reward_points: 75,
    reward_coins: 1500,
    type: 'contributor',
    difficulty: 'medium',
    done: false,
  }
];

// sample recordings data
export const mockRecordings = [
  {
    id: 'rec_001',
    user_id: 'user_001',
    user_name: 'Siti Nurhaliza',
    mission_id: 'mission_001',
    audio_url: '/audio/sample1.mp3',
    transcript_ai: 'Gak ana uwong sing bisa nglirwakake kabeh',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-15T10:30:00Z',
    contribution_type: 'voice',
    languageName: 'Jawa',
    dialect: 'Jawa Ngoko',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_002',
    user_id: 'user_002',
    user_name: 'Ahmad Dahlan',
    mission_id: 'mission_002',
    audio_url: '/audio/sample2.mp3',
    transcript_ai: 'Rang mudo kudu tau tatakramo',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-16T14:20:00Z',
    contribution_type: 'voice',
    languageName: 'Sunda',
    dialect: 'Sunda Priangan',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_003',
    user_id: 'user_003',
    user_name: 'Luh Ketut Ayu',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-17T09:15:00Z',
    contribution_type: 'vocabulary',
    languageName: 'Bali',
    dialect: 'Bali Alus',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_004',
    user_id: 'user_004',
    user_name: 'Raden Wijaya',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'approved',
    validated_at: '2024-01-18T11:00:00Z',
    created_at: '2024-01-17T16:45:00Z',
    contribution_type: 'folktale',
    languageName: 'Jawa',
    dialect: 'Jawa Krama',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_005',
    user_id: 'user_005',
    user_name: 'Andi Mappasessu',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'approved',
    validated_at: '2024-01-19T14:30:00Z',
    created_at: '2024-01-18T08:20:00Z',
    contribution_type: 'vocabulary',
    languageName: 'Bugis',
    dialect: 'Bugis Bone',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'bugis',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  },
  {
    id: 'rec_006',
    user_id: 'user_006',
    user_name: 'Putu Gede Agung',
    mission_id: '',
    audio_url: '',
    transcript_ai: '',
    transcript_human: '',
    status: 'pending',
    created_at: '2024-01-19T16:00:00Z',
    contribution_type: 'translation',
    languageName: 'Bali',
    dialect: 'Bali Lumrah',
    region: [6],
    province: [6],
    language: '1',
    ethnic: 'Jawa',
    text: 'Mangan',
    textTranslation: 'Makan',
    sentence: 'Mangan kiye bae, lewih enak.',
    sentenceTranslation: 'Makan ini saja, lebih enak.',
    notes: 'Kata kerja',
    textAudio: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
  }
];

// sample province data
export const provinceList = [
  { value: 1, label: "Aceh" },
  { value: 2, label: "Sumatera Barat" },
  { value: 3, label: "Jawa Tengah" },
  { value: 4, label: "Jawa Timur" },
  { value: 5, label: "Bali" },
  { value: 6, label: "Daerah Istimewa Yogyakarta" }
];

// sample region data
export const regionList = [
  { value: 1, label: "Purbalingga" },
  { value: 2, label: "Batam" },
  { value: 3, label: "Sleman" },
  { value: 4, label: "Bantul" },
  { value: 5, label: "Pekanbaru" },
  { value: 6, label: "Yogyakarta" },
];

// sample comment data
export const comments = [
  {
    "id": "c1f7e3a1-74c3-4d6e-a6e0-1ae54a07f11b",
    "photo": "https://randomuser.me/api/portraits/men/11.jpg",
    "name": "Andi Pratama",
    "date": "2025-02-10T14:32:00Z",
    "comment": "Menurut saya arti kata ini sudah tepat, tetapi contoh kalimatnya bisa dibuat lebih natural.",
    "likes": 12,
    "replies": [
      {
        "id": "7fb8d2a3-0c83-4c44-8c06-97cf67c3e581",
        "photo": "https://randomuser.me/api/portraits/women/21.jpg",
        "name": "Siti Rahmawati",
        "date": "2025-02-10T15:12:00Z",
        "comment": "Betul, saya setuju. Saya bisa bantu buatkan contoh kalimat lain nanti.",
        "likes": 5,
        "replies": []
      }
    ]
  },
  {
    "id": "b4e684b7-d4ac-4362-a784-f3f02d178e91",
    "photo": "https://randomuser.me/api/portraits/women/14.jpg",
    "name": "Maria Lestari",
    "date": "2025-02-11T09:21:00Z",
    "comment": "Kata ini umum dipakai di daerah saya, biasanya untuk percakapan sehari-hari.",
    "likes": 8,
    "replies": []
  },
  {
    "id": "0e1c995e-07df-4d96-8c4f-f4b3d8fb5a88",
    "photo": "https://randomuser.me/api/portraits/men/32.jpg",
    "name": "Budi Santoso",
    "date": "2025-02-11T10:02:00Z",
    "comment": "Apakah kata ini termasuk ragam ngoko atau krama?",
    "likes": 3,
    "replies": [
      {
        "id": "3d8a241b-e2bd-4907-865c-15e22d5c5fa8",
        "photo": "https://randomuser.me/api/portraits/men/45.jpg",
        "name": "Ari Wibowo",
        "date": "2025-02-11T10:30:00Z",
        "comment": "Setahu saya ini ragam ngoko, tapi bisa dipakai di percakapan santai antar teman.",
        "likes": 2,
        "replies": []
      }
    ]
  },
  {
    "id": "069cfc07-3cf2-4fc8-9ddb-2e7f0c6a49dd",
    "photo": "https://randomuser.me/api/portraits/women/36.jpg",
    "name": "Dewi Ayu",
    "date": "2025-02-12T08:15:00Z",
    "comment": "Saya baru tahu arti kata ini, terima kasih informasinya!",
    "likes": 15,
    "replies": []
  },
  {
    "id": "ac58c0be-f831-4db6-a43a-06a1f43d4d8e",
    "photo": "https://randomuser.me/api/portraits/men/19.jpg",
    "name": "Rizky Maulana",
    "date": "2025-02-12T12:44:00Z",
    "comment": "Contoh kalimatnya kurang jelas konteksnya, mungkin bisa diperbaiki.",
    "likes": 4,
    "replies": [
      {
        "id": "6e1a8e1f-89d3-452e-a765-22565f59dbcc",
        "photo": "https://randomuser.me/api/portraits/women/22.jpg",
        "name": "Putri Agustina",
        "date": "2025-02-12T13:01:00Z",
        "comment": "Baik, saya coba revisi dan kirimkan contoh baru besok.",
        "likes": 1,
        "replies": []
      }
    ]
  },
  {
    "id": "d75e4c7a-9de1-4cd4-9b26-70eb52d37df4",
    "photo": "https://randomuser.me/api/portraits/men/55.jpg",
    "name": "Fajar Nugroho",
    "date": "2025-02-12T17:22:00Z",
    "comment": "Ini kata yang sering saya dengar waktu kecil, jadi nostalgia.",
    "likes": 19,
    "replies": []
  },
  {
    "id": "4f91d7b8-5e6e-49b0-b9dc-13c4f8dd4e70",
    "photo": "https://randomuser.me/api/portraits/women/28.jpg",
    "name": "Lina Komalasari",
    "date": "2025-02-13T07:11:00Z",
    "comment": "Apakah ada variasi pelafalan kata ini di daerah lain?",
    "likes": 6,
    "replies": [
      {
        "id": "834abebf-47d8-4b56-bd7c-79c4ddd2c3e2",
        "photo": "https://randomuser.me/api/portraits/men/27.jpg",
        "name": "Dimas Aditya",
        "date": "2025-02-13T07:30:00Z",
        "comment": "Ada beberapa. Di daerah saya huruf vokalnya sedikit berbeda.",
        "likes": 3,
        "replies": []
      }
    ]
  },
  {
    "id": "d3409437-7afc-4edd-b2c4-f2e03d951740",
    "photo": "https://randomuser.me/api/portraits/men/61.jpg",
    "name": "Joko Widodo",
    "date": "2025-02-13T10:55:00Z",
    "comment": "Bagus sekali penjelasannya. Sangat bermanfaat!",
    "likes": 22,
    "replies": []
  },
  {
    "id": "f8adf5bb-c5c3-4a8e-bc48-6381be942fc6",
    "photo": "https://randomuser.me/api/portraits/women/33.jpg",
    "name": "Nadia Safitri",
    "date": "2025-02-13T12:02:00Z",
    "comment": "Mungkin bisa ditambahkan audio cara pengucapannya.",
    "likes": 14,
    "replies": []
  },
  {
    "id": "5bc117e5-0a2a-4f83-b8f6-4e6439086f88",
    "photo": "https://randomuser.me/api/portraits/men/40.jpg",
    "name": "Teguh Hartanto",
    "date": "2025-02-14T09:45:00Z",
    "comment": "Apakah kata ini masih dipakai pada generasi muda sekarang?",
    "likes": 5,
    "replies": [
      {
        "id": "9dcb061a-5c43-4af6-bfff-487282a61b8e",
        "photo": "https://randomuser.me/api/portraits/women/40.jpg",
        "name": "Rara Permata",
        "date": "2025-02-14T10:10:00Z",
        "comment": "Masih, tapi mulai jarang. Biasanya dipakai di lingkungan keluarga.",
        "likes": 4,
        "replies": []
      }
    ]
  }
];

// sample data game level 1
export const QUIZ_ITEMS_LEVEL_1 = [
  {
    id: "1",
    indonesia: "makan",
    correct: "mangan",
    question: "Sobat RANA! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "turu", mean: "tidur" },
      { id: "2", name: "mangan", mean: "makan" },
      { id: "3", name: "mlayu", mean: "Berlari" },
      { id: "4", name: "njagong", mean: "duduk" },
      { id: "5", name: "nginum", mean: "minum" },
    ],
  },
  {
    id: "2",
    indonesia: "Melihat",
    correct: "Ndeleng",
    question: "Sobat RANA! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Lungguh", mean: "Duduk" },
      { id: "2", name: "Turu", mean: "Tidur" },
      { id: "3", name: "Ndeleng", mean: "Melihat" },
      { id: "4", name: "Mlayu", mean: "Berlari" },
      { id: "5", name: "Maca", mean: "Membaca" },
    ],
  },
  {
    id: "3",
    indonesia: "Baju",
    correct: "Klambi",
    question: "Sobat RANA! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Mlaku", mean: "Berjalan" },
      { id: "2", name: "Pit", mean: "Sepeda" },
      { id: "3", name: "Tèng", mean: "Ke" },
      { id: "4", name: "Klambi", mean: "Baju" },
      { id: "5", name: "Pring", mean: "Bambu" },
    ],
  },
  {
    id: "4",
    indonesia: "Minum",
    correct: "Ngombé",
    question: "Sobat RANA! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Ngombé", mean: "Minum" },
      { id: "2", name: "Mangan", mean: "Makan" },
      { id: "3", name: "Mlaku", mean: "Berjalan" },
      { id: "4", name: "Turu", mean: "Tidur" },
      { id: "5", name: "Nggawa", mean: "Membawa" },
    ],
  },
  {
    id: "5",
    indonesia: "Berjalan",
    correct: "Mlaku",
    question: "Sobat RANA! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Ngaso", mean: "Istirahat" },
      { id: "2", name: "Mlayu", mean: "Berlari" },
      { id: "3", name: "Mlaku", mean: "Berjalan" },
      { id: "4", name: "Nggawa", mean: "Membawa" },
      { id: "5", name: "Turu", mean: "Tidur" },
    ],
  },
];

// sample data game level 2
export const QUIZ_ITEMS_LEVEL_2 = [
  {
    id: "1",
    indonesia: "Saya berdiri",
    correct: "Nyong njanggleng",
    question: "Sobat RANA! Selamat telah menyelesaikan level 1 dengan luar biasa! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Nyong njanggleng", mean: "Saya berdiri" },
      { id: "2", name: "Nyong lungguh", mean: "Saya duduk" },
      { id: "3", name: "Nyong mlayu", mean: "Saya berlari" },
      { id: "4", name: "Koe mlaku", mean: "Kamu berjalan" },
      { id: "5", name: "Koe tangi", mean: "Kamu bangun" },
    ],
  },
  {
    id: "2",
    indonesia: "Kamu membaca",
    correct: "Koe maca",
    question: "Sobat RANA! Selamat telah menyelesaikan level 1 dengan luar biasa! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Koe nulis", mean: "Kamu menulis" },
      { id: "2", name: "Nyong ngombé", mean: "Saya minum" },
      { id: "3", name: "Koe maca", mean: "Kamu membaca" },
      { id: "4", name: "Koe mlaku", mean: "Kamu berjalan" },
      { id: "5", name: "Nyong turu", mean: "Saya tidur" },
    ],
  },
  {
    id: "3",
    indonesia: "Saya ingin pergi",
    correct: "Nyong arep lunga",
    question: "Sobat RANA! Selamat telah menyelesaikan level 1 dengan luar biasa! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Nyong wis mlaku", mean: "Saya sudah berjalan" },
      { id: "2", name: "Nyong arep lunga", mean: "Saya mau pergi" },
      { id: "3", name: "Koe arep ngaso", mean: "Kamu mau istirahat" },
      { id: "4", name: "Koe wis turu", mean: "Kamu sudah tidur" },
      { id: "5", name: "Mangan", mean: "Makan" },
    ],
  },
  {
    id: "4",
    indonesia: "Dia sudah lapar",
    correct: "Kae wis kencot",
    question: "Sobat RANA! Selamat telah menyelesaikan level 1 dengan luar biasa! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Nyong wis mangan", mean: "Saya sudah makan" },
      { id: "2", name: "Kae wis kencot", mean: "Dia sudah lapar" },
      { id: "3", name: "Koe urung mangan", mean: "Kamu belum makan" },
      { id: "4", name: "Nyong urung mangan", mean: "Saya belum makan" },
      { id: "5", name: "Kae urung kencot", mean: "Dia belum lapar" },
    ],
  },
  {
    id: "5",
    indonesia: "Aku menjemputmu",
    correct: "Nyong nyamper koe",
    question: "Sobat RANA! Selamat telah menyelesaikan level 1 dengan luar biasa! Tarik dan letakkan kata berikut sesuai dengan bahasa ngapaknya! Kalian yang berhasil memasangkan kata dengan tepat dan cepat akan mendapatkan skor maksimal!",
    options: [
      { id: "1", name: "Nyong nyamper koe", mean: "Saya menjemputmu" },
      { id: "2", name: "Koe dolan karo nyong", mean: "Kamu bermain bersamaku" },
      { id: "3", name: "Kae nyamper koe", mean: "Dia menjemput kamu" },
      { id: "4", name: "Nyong arep nyamper", mean: "Saya mau menjemput" },
      { id: "5", name: "Koe wis nyamper nyong", mean: "Kamu sudah menjemputku" },
    ],
  },
];

// sample data level
export const QUIZ_LEVELS = [
  {
    id: "1",
    title: "Level 1 (Kosakata)",
    description: "Pasangkan kosakata bahasa indonesia sesuai dengan bahasa ngapaknya!",
    questions: 5,
    locked: false,
    details: QUIZ_ITEMS_LEVEL_1,
  },
  {
    id: "2",
    title: "Level 2 (Frasa)",
    description: "Pasangkan frasa bahasa indonesia berikut sesuai dengan bahasa ngapaknya!",
    questions: 5,
    locked: true,
    details: QUIZ_ITEMS_LEVEL_2,
  },
];

// sample language quiz
export const languageArchiveQuiz = [
  {
    id: "1",
    name: "Bahasa Jawa Banyumasan",
    region: "Jawa Tengah",
    regionId: ["33"],
    ethnic: "Jawa",
    speakers: "84,3 juta",
    status: "recorded",
    vocabularyCount: 2500,
    audioCount: 1200,
    contributorCount: 300,
  },
];